### ISSUE TITLE
env file structure

### ISSUE THREAD

**Issue by leonardodincalci** [ashrafchowdury/dotemd#75]
Hello, I'm trying to made a correct env file without success.

I added this:

NEXT_PUBLIC_APPWRITE_PROJECT_URL=***
NEXT_PUBLIC_APPWRITE_PROJECT_ID=***

NEXT_APPWRITE_DATABASE_ID=***
NEXT_APPWRITE_COLLECTION_ID=***

And also, how appwrite database and collection structured? Have attributes or not?

I received this error in localhost "AppwriteException: User (role: guests) missing scope (account)" and disappear if try login. 
Also GitHub login show me missing redirect url.

**Comment by ashrafchowdury** [comment]
Thanks for creating the issue, @leonardodincalci 👍

- If you want to restructure the env file you can do it, the restructure looks great.

- [The appwrite database and collection are structured] by these **attributes**: `template`, `title`, and `userId`.

- [The error in localhost `"AppwriteException: User (role: guests) missing scope (account)"`] I'm trying to figure out what's happening.
- [GitHub login show me missing redirect URL] I think we forget to add the redirecting URL on GitHub auth function.

**Comment by ashrafchowdury** [comment]
Thanks for creating the issue, @leonardodincalci 👍

Add these to your .env file with their values:

NEXT_PUBLIC_APPWRITE_PROJECT_URL=***
NEXT_PUBLIC_APPWRITE_PROJECT_ID=***

- [The appwrite database and collection are structured] by these attributes: template, title, and userId.

- [The error in localhost "AppwriteException: User (role: guests) missing scope (account)"] I'm trying to figure out what's happening.

- [GitHub login show me missing redirect URL] I think we forget to add the redirecting URL on GitHub auth function.
